# curl -X 'POST'
#  'https://editor.swagger.io/project'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "description": "string",
#  "name": "string",
#  "userId": 0
#}'
POST http://localhost:1236/api/v1/project
accept: application/json
Content-Type: application/json

{
  "description": "Test Project",
  "name": "Test Project",
  "userId": 1
}

###

